latifalar = [
    "O'qituvchi: - Bolalar, kim o'zini tentak deb hisoblasa, o'rnidan tursin! \n Vanya turibdi. \n O'qituvchi: - Vanya, sen o'zingni tentak deb hisoblaysanmi? \n Vanya: - Yo‘q, lekin bir o‘zim o‘tirib, sizni tentak deb o‘ylash uyat bo‘ldi.",
    "Odam: - Shifokor, men hech narsani eslay olmayapman! \n Shifokor: - Qachon boshlandi bu muammo? \n Odam: - Qaysi muammo?",
    "O‘qituvchi: - Kim o‘zining ideal og‘irligini biladi? \n Vova: - Ha, men bilaman. \n O‘qituvchi: - Qanday qilib aniqlading? \n Vova: - Har safar vaznim oshsa, onam: 'Endi yetarli, bas!' deydi.",
    "Bola: - Dada, menga dinozavr olib bering! \n Dadasi: - Bo‘g‘ri bolam, ular yo‘qolib ketgan! \n Bola: - Bo‘lsa-da harakat qilib ko‘ring!",
    "Doktor: - Sizga choy yoki qahva ichishni tavsiya qilaman. \n Bemar: - Qaysi biri yaxshiroq? \n Doktor: - Men shunchaki tavsiya qilaman, qarorni xotinim qabul qiladi.",
    "Bolakay do‘stidan so‘raydi: - Agar sening ikki dollaring bo‘lsa va men sendan birini so‘rasam, menga berasanmi? \n Do‘sti: - Albatta. \n Bolakay: - Afsus, sen mendan yaxshiroq odam ekanligingni isbotlading.",
    "Mijoz: - Ofitsiant, bu sho‘rva juda sho‘r! \n Ofitsiant: - Demak, sizga sho‘rva yoqmaganmi? \n Mijoz: - Yo‘q, men o‘rta tuzli sho‘rvalarni yaxshi ko‘raman! \n Ofitsiant: - Unda, bitta suv olib kelay, aralashtirib ichasiz.",
    "Bola: - Dada, bizda eng katta hayvon qaysi? \n Dadasi: - Fil. \n Bola: - Undan kattarog‘i yo‘qmi? \n Dadasi: - Bor, kredit qarzi.",
    "Talaba: - Ustoz, testlar javoblarini o‘zim yozsam bo‘ladimi? \n Ustoz: - Ha, albatta! \n Talaba: - Ruxsat berasizmi? \n Ustoz: - Albatta. Lekin to‘g‘ri javoblarni yozing!",
    "Hakam futbolchiga: - Sen nega maydonda shunchalik yomon o‘ynayapsan? \n Futbolchi: - Chunki onam bugun o‘yinni televizorda ko‘rayapti. \n Hakam: - Bo‘pti, onangga hush keladigan bir narsa qil! \n Futbolchi: - Mayli, unga salom yo‘llayman!"
]
yhq_qoidalari = [
    "Transport vositasini boshqarishdan oldin haydovchilik guvohnomasiga ega bo‘lish kerak.",
    "Yo‘lda harakatlanayotganda tezlik chegaralariga rioya qilish shart.",
    "Svetofor qizil chirog‘i yonib turganda to‘xtash majburiy.",
    "Piyodalarga belgilangan piyodalar yo‘laklarida yo‘l berish kerak.",
    "Har qanday transport vositasi burilishdan oldin burilish ishorasini yoqishi shart.",
    "Spirtli ichimlik iste’mol qilib mashina haydash qat’iyan taqiqlanadi.",
    "Yo‘lda boshqa transport vositalariga to‘sqinlik qilmaslik va belgilangan harakat yo‘nalishida yurish kerak.",
    "Yo‘lda qatnashayotgan barcha yo‘lovchilar xavfsizlik kamarlarini taqib yurishi lozim.",
    "Avtotransport vositalari o‘rtasida xavfsiz masofani saqlash kerak.",
    "Yo‘llarda telefon yoki boshqa chalg‘ituvchi vositalardan foydalanib transport vositasini boshqarish taqiqlanadi."
]
fitnes_malumotlari = [
    "Har kuni kamida 30 daqiqa jismoniy faollik bilan shug‘ullanish sog‘liq uchun foydalidir.",
    "Kuchli mushaklarni rivojlantirish uchun og‘irlik mashqlari (strength training) muhim.",
    "Kardiomashg‘ulotlar yurak va qon tomir tizimi uchun foydali bo‘lib, kaloriyalarni tezroq yoqishga yordam beradi.",
    "Mashg‘ulotlardan oldin va keyin stretching qilish mushaklarning shikastlanishining oldini oladi.",
    "Tanani rivojlantirish uchun mashqlarni har xil turlarini bajarish foydalidir (kardio, kuch mashqlari, muvozanat mashqlari).",
    "To‘g‘ri ovqatlanish fitnes natijalariga erishishda 70% ahamiyatga ega.",
    "Mushaklarning tiklanishi uchun yetarlicha uxlash va dam olish juda muhim.",
    "Mashg‘ulot paytida suv ichish tanani gidratatsiya qilish va samaradorlikni oshirishga yordam beradi.",
    "Progressni kuzatish uchun jismoniy o‘lchovlar, vazn va kuchning rivojlanishini yozib borish foydalidir.",
    "Fitnesga rioya qilishda sabr-toqat va davomiylik muhim. Natijalar vaqt o‘tishi bilan ko‘rinadi."
]
donishmand_maslahatlari = [
    "Har qanday vaziyatda ham sabrli bo‘l, chunki sabr eng katta kuchdir.",
    "Bilim izlashdan hech qachon to‘xtama, chunki haqiqiy boylik – bu aql.",
    "Har doim odamlarga yaxshi muomala qil, chunki yaxshi so‘z yuraklarni ochadi.",
    "Do‘stlaringni sinash uchun qiyin paytlarda ularning yoningda bo‘lishini kuzat.",
    "Dangasalikdan uzoq bo‘l, chunki muvaffaqiyat harakatga bog‘liq.",
    "Har kuni ozgina bo‘lsa ham yaxshilik qil, chunki yaxshilik insonning qadrini oshiradi.",
    "Pulni topish ham, uni saqlash ham san’at. Pulni boshqarishni o‘rgan.",
    "O‘tgan kuning bugunning tajribasi, kelajaging esa bugunning natijasi.",
    "O‘z ustingda ishlashni hech qachon to‘xtatma, chunki doimiy rivojlanish muvaffaqiyat garovidir.",
    "Hayotdagi eng katta boylik – sog‘liq va tinchlik. Ularni qadrlashni o‘rgan."
]
taomlar_retsepti = [
    "Palov:\n   - Masalliqlar: 500 g guruch, 500 g go‘sht, 2 dona sabzi, 2 dona piyoz, 100 ml o‘simlik yog‘i, tuz, ziravorlar.\n   - Tayyorlash: Piyozni qovurib, go‘sht qo‘shiladi. So‘ng sabzi solinib, qovuriladi. Ustidan suv quyilib, guruch solinadi va past olovda dimlanadi.",
    
    "Sho‘rva:\n   - Masalliqlar: 500 g go‘sht, 2 ta kartoshka, 1 ta sabzi, 1 ta piyoz, pomidor, tuz, ziravorlar.\n   - Tayyorlash: Go‘shtni suvga solib qaynatiladi. Sabzi, piyoz, kartoshka mayda to‘g‘ralib, sho‘rvaga qo‘shiladi va past olovda tayyor bo‘lguncha pishiriladi.",
    
    "Manty:\n   - Masalliqlar: 500 g un, 250 ml suv, 500 g go‘sht, 2 ta piyoz, tuz, ziravorlar.\n   - Tayyorlash: Un va suvdan xamir qoriladi. Go‘sht va piyoz qiymalanib, ziravorlar qo‘shiladi. Xamir yoyilib, ichiga qiymadan solinadi va bug‘da pishiriladi.",
    
    "Lag‘mon:\n   - Masalliqlar: 500 g un, 300 g go‘sht, 1 ta sabzi, 1 ta piyoz, 1 ta pomidor, 1 ta bulg‘or qalampiri, sarimsoq piyoz.\n   - Tayyorlash: Xamir tayyorlanib, cho‘zilib, qaynatiladi. Go‘sht va sabzavotlar qovurilib, ustiga suv solinadi. Tayyor sho‘rva lag‘mon ustiga quyiladi.",
    
    "Chuchvara:\n   - Masalliqlar: 500 g un, 250 ml suv, 400 g go‘sht, 1 ta piyoz, tuz, ziravorlar.\n   - Tayyorlash: Xamir tayyorlanib, yoyiladi. Go‘sht qiymalanib, piyoz bilan aralashtiriladi. Xamir ichiga solinib, qaynagan suvda pishiriladi.",
    
    "Somsa:\n   - Masalliqlar: 500 g un, 250 ml suv, 500 g go‘sht, 2 ta piyoz, yog‘, tuz, ziravorlar.\n   - Tayyorlash: Xamir qorilib, yoyiladi. Go‘sht va piyoz qiymalanib, ichiga solinadi. Uchburchak shaklida tugilib, tandir yoki pechda pishiriladi.",
    
    "Mastava:\n   - Masalliqlar: 200 g guruch, 200 g go‘sht, 1 ta sabzi, 1 ta piyoz, pomidor, kartoshka, tuz, ziravorlar.\n   - Tayyorlash: Piyoz va sabzi qovurilib, go‘sht solinadi. Pomidor va kartoshka qo‘shilib, suv quyiladi. Guruch solinib, past olovda pishiriladi.",
    
    "Norin:\n   - Masalliqlar: 500 g un, 300 g go‘sht, piyoz, qalampir, ziravorlar.\n   - Tayyorlash: Xamir tayyorlanib, yupqa qilib yoyiladi va pishiriladi. So‘ng ingichka qilib kesiladi. Go‘sht mayda to‘g‘ralib, xamir bilan aralashtiriladi va ustiga ziravorlar sepiladi.",
    
    "Qozon kabob:\n   - Masalliqlar: 500 g go‘sht, 2 ta kartoshka, 1 ta piyoz, 1 ta sabzi, yog‘, tuz, ziravorlar.\n   - Tayyorlash: Qozonga yog‘ solinib, go‘sht, kartoshka va sabzavotlar terib chiqiladi. Ustidan tuz va ziravorlar qo‘shilib, past olovda dimlanadi.",
    
    "Osh (Beshbarmoq):\n   - Masalliqlar: 500 g qo‘y go‘shti, 500 g un, 2 ta piyoz, tuz, ziravorlar.\n   - Tayyorlash: Go‘sht suvda qaynatiladi. Xamir yupqa qilib yoyilib, qaynatilgan go‘sht suvida pishiriladi. Ustiga go‘sht va piyoz solinib, taqdim etiladi."
]
motivations = [
    "Hech narsaga erisha olmasang, hech bo‘lmaganda kech tushunib yetganingni tan ol.",
    "Orzularingni ro‘kach qilaverma, qachon harakatni boshlaysan?",
    "Har kuni bahona topaverishingni hech kim eshitishni ham xohlamaydi.",
    "Agar shu tempda davom etsang, 10 yildan keyin ham xuddi shu joyda qolasan.",
    "Sen dangasa emassan, shunchaki o‘z hayotingni barbod qilishda davom etyapsan.",
    "Hamma imkoniyat bor, faqat sen yetarlicha harakat qilmayapsan.",
    "Agar puling bo‘lmasa, gapirmasang ham bo‘ladi. Pul ishlashni o‘rgan!",
    "O‘zgarishni xohlamasang, hech kim seni kuchli qilish uchun kelmaydi.",
    "Agar kech uyg‘onib, bekorchi odatlaringni tashlamasang, umring o‘tib ketaveradi.",
    "Sen qancha bahona topma, baribir dunyo oldinga yuraveradi, sen esa joyingda qolaverasan."
]
positive_words = [
    "Sen kuchlisan! Har bir qadam seni maqsadingga yaqinlashtiradi! 💪",
    "Bugun ajoyib kun bo‘ladi! Faqat oldinga! 🚀",
    "Sen muvaffaqiyatga loyiqsan! Uni olish uchun harakat qil! 🌟",
    "Har bir kichik qadam katta natijalarga olib keladi! ✨",
    "Dunyo seni tabassum bilan kutmoqda! 😊",
    "Hech narsa imkonsiz emas! Faqat sinab ko‘r! 🔥",
    "Sen o‘z hayotingning qahramonisan! 🎯",
    "Bugun nimadir yangi narsani o‘rgan va undan zavq ol! 📚",
    "Sening energiyang va harakating kelajagingni yaratadi! 💡",
    "O‘zingni sev, o‘z ustingda ishlashda davom et va natijadan zavqlan! 💖"]

yangiliklar = [
        "Bugun bozor narxlari ko'tarildi.",
        "Yangi smartfon modeli taqdim etildi.",
        "Chempionatda kuchli jamoalar o'rtasida o'yin bo'lib o'tdi.",
        "Dunyo bo'ylab iqtisodiy o'sish pasaydi.",
        "Ilm-fan sohasida yangi kashfiyot qilindi.",
        "Kriptovalyuta bozori katta o‘zgarishlarni boshdan kechirmoqda.",
        "Bugun O‘zbekiston milliy terma jamoasi o‘yin o'tkazdi.",
        "AI va robototexnika sohasida inqilobiy texnologiyalar paydo bo‘ldi.",
        "Dunyoda eng katta savdo markazi ochildi.",
        "Yerning eng chekka nuqtasida yangi hayvon turlari topildi.",
        "Dunyoning eng yaxshi universitetlari reytingi yangilandi.",
        "Yangi avtomobil modeli haydovchilar orasida katta qiziqish uyg‘otdi.",
        "Internet tezligi bo‘yicha rekord o‘rnatildi.",
        "Samolyot ishlab chiqaruvchi kompaniya yangi modelini taqdim etdi.",
        "Iqlim o‘zgarishi tufayli dengiz sathining ko‘tarilishi davom etmoqda.",
        "Futbol yulduzi yangi klubga o‘tdi.",
        "Sun'iy intellekt yordamida yangi dorilar ishlab chiqildi.",
        "Ilmiy jamoa Marsda suv izlarini topdi.",
        "Milliy valyutaning kursi bugun o‘zgarishsiz qoldi.",
        "Eng yirik texnologik kompaniyalar AI bo‘yicha hamkorlikni boshladi.",
        "Netflix yangi seriali rekord darajadagi tomoshabin to‘pladi.",
        "Yangi elektromobil bozorda katta shov-shuvga sabab bo‘ldi.",
        "Kosmosga sayohat qilish bo‘yicha yangi kompaniya ishga tushirildi.",
        "Koinotdan kelgan sirli signal haqida yangi tadqiqot e’lon qilindi.",
        "Mashhur biznesmen yangi startap ochdi.",
        "Buxoro shahrida yangi sayyohlik markazi ochildi.",
        "Ilmiy olimlar xotirani mustahkamlash bo‘yicha yangi usulni topdi.",
        "Dunyoda eng katta to‘lqinli elektr stansiya ishga tushirildi.",
        "Mashhur yozuvchi yangi kitobini e’lon qildi.",
        "Yevropada yangi texnologiyalar festivali boshlandi.",
        "AI yordamida inson yuz ifodalarini to‘g‘ri tushunish texnologiyasi yaratildi.",
        "Shahar transport tizimida yangi ekologik toza avtobuslar paydo bo‘ldi.",
        "Apple yangi iPhone modelini taqdim etdi.",
        "Olimlar yadro qurolining xavfsizligini oshirish bo‘yicha tadqiqot olib bordi.",
        "Yangi sun’iy intellekt tizimi tibbiyotda qo‘llanilmoqda.",
        "Dunyo bo‘ylab kitob o‘qish bo‘yicha yangi trend paydo bo‘ldi.",
        "Bolalar uchun yangi interaktiv ta’lim platformasi yaratildi.",
        "Mashhur san’atkor yangi albomini chiqardi.",
        "Iqlim o‘zgarishi tufayli qurg‘oqchilik muammosi keskinlashmoqda.",
        "Bugun aksiyalar bozorida katta o‘zgarishlar kuzatildi.",
        "Kriptovalyuta dunyosida yangi innovatsion loyihalar paydo bo‘ldi.",
        "Mashhur futbol jamoasi yangi bosh murabbiyini tanladi.",
        "Kosmik tadqiqotlar bo‘yicha yangi loyiha ishga tushirildi.",
        "Mashhur aktyor yangi filmda bosh rolni ijro etadi.",
        "Yer atmosferasida katta meteor kuzatildi.",
        "Dunyoda eng yaxshi restoranlar reytingi yangilandi.",
        "Smartfon ishlab chiqaruvchi kompaniya yangi texnologiyani taqdim etdi.",
        "Olimlar inson umrini uzaytirish bo‘yicha yangi tadqiqot o‘tkazmoqda.",
        "Dunyo bo‘ylab eng tez rivojlanayotgan startaplar aniqlandi.",
        "Mashhur avtomobil brendi o‘zining yangi modelini namoyish etdi.",
        "Quyosh energiyasidan foydalanish bo‘yicha yangi loyiha amalga oshirildi.",
        "Kriptovalyutalar bo‘yicha yangi qonunlar qabul qilindi.",
        "Eng yaxshi texnologik mahsulotlar ro‘yxati e’lon qilindi.",
        "Shaharlarda elektr transport tizimi kengaymoqda.",
        "Dunyoda eng qimmat san’at asarlari sotuvga qo‘yildi.",
        "O‘zbekiston iqtisodiy o‘sish sur’ati bo‘yicha yangi ma’lumotlar e’lon qilindi.",
        "Yangi elektromobil bozorda rekord darajadagi buyurtmalar oldi.",
        "Marsda yashash imkoniyatlari bo‘yicha yangi tadqiqotlar olib borilmoqda.",
        "Dunyodagi eng katta kutubxona o‘z eshiklarini ochdi.",
        "Internet xavfsizligi bo‘yicha yangi chora-tadbirlar ishlab chiqildi.",
        "Sun’iy intellekt orqali yangi dasturlar ishlab chiqilmoqda.",
        "Kompaniyalar o‘z mahsulotlarini yanada ekologik toza qilishga harakat qilmoqda.",
        "Kosmik sayohatlarning narxi kelajakda arzonlashishi mumkin.",
        "Dunyo bo‘ylab yangi bank tizimlari rivojlanmoqda.",
        "Dunyoda eng katta ko‘prik qurib bitkazildi.",
        "O‘zbekiston yangi energetika loyihalarini ishga tushirdi.",
        "Mashhur ixtirochi yangi texnologiyasini namoyish etdi.",
        "Dunyodagi eng yaxshi universitetlarning talabalari yirik tanlovda qatnashmoqda.",
        "Olimlar insonning miyasini to‘g‘ridan-to‘g‘ri kompyuter bilan bog‘lash loyihasini sinovdan o‘tkazmoqda.",
        "Kichik biznes uchun yangi imkoniyatlar yaratildi.",
        "Elektr transport vositalari bozori tez sur’atda o‘smoqda.",
        "Ekologik toza texnologiyalar bo‘yicha xalqaro anjuman o‘tkazildi.",
        "Bugungi kunda internet foydalanuvchilari soni 5 milliarddan oshdi.",
        "Yer atmosferasida yangi turdagi gazlar topildi.",
        "Suv resurslarini tejash bo‘yicha yangi texnologiya yaratildi.",
        "Bugun yangi tarixiy arxeologik topilma aniqlandi.",
        "Kriptovalyuta savdosi yangi bosqichga o‘tdi.",
        "Yangi avtomatlashtirilgan tizim orqali bank operatsiyalari tezlashdi.",
        "Shifokorlar yangi gen terapiyasini muvaffaqiyatli sinovdan o‘tkazishdi.",
        "Mashhur dasturchi yangi dasturiy ta’minotni taqdim etdi.",
        "Sun’iy intellekt yordamida yangi mobil ilovalar ishlab chiqilmoqda.",
        "Dunyo bo‘ylab sayyohlik biznesi o‘sishda davom etmoqda.",
        "Mashhur brend yangi mahsulotlar liniyasini e’lon qildi.",
        "Dunyodagi eng katta texnologik kompaniyalar yangi hamkorlik shartnomalari imzoladi.",
        "Futbol bo‘yicha jahon chempionati uchun stadionlar tayyorlanmoqda."
    ]